version: '3.8'

services:
  api:
    image: ${REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-your-username/your-repo}/api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    image: ${REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-your-username/your-repo}/frontend:latest
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8080
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 