CREATE TABLE IF NOT EXISTS persons (
    id SERIAL PRIMARY KEY,
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create index for JSONB data
CREATE INDEX IF NOT EXISTS idx_persons_data ON persons USING GIN (data); 