apiVersion: apps/v1
kind: Deployment
metadata:
  name: dodle-frontend
spec:
  revisionHistoryLimit : 0
  selector:
    matchLabels:
      app: dodle-frontend
  template:
    metadata:
      labels:
        app: dodle-frontend
    spec:
      containers:
        - name: frontend
          image: proxyfil/dodle-front:0.0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "https://dodle-api.do-polytech.fr"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
