name: Frontend Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'front/**'
      - '.github/workflows/front-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'front/**'
      - '.github/workflows/front-tests.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './front/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Kaniko
      uses: imjasonh/setup-kaniko@v0.1
      with:
        kaniko-version: latest

    - name: Build and push image
      run: |
        /kaniko/executor \
          --context ${{ github.workspace }}/front \
          --dockerfile ${{ github.workspace }}/front/Dockerfile \
          --destination ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }} \
          --destination ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
          --destination ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          --cache=true \
          --cache-repo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/cache

    - name: Scan image for vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH' 