name: Update person for the day
on:
  schedule:
    - cron: "01 00 * * *"

jobs:
  update-person:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to update person
        run: |
          curl -X GET -H 'Api-Token: ${{ secrets.API_TOKEN }}' \
          "https://dodle-api.do-polytech.fr/private/v1/guess/person/create"