name: Update person for the day
on:
  schedule:
    - cron: "42 23 * * *"

jobs:
  update-person:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to update person
        run: |
          curl -X GET "https://dodle-api.do-polytech.fr/private/v1/guess/person/create" \
          -H API-Token "${{ secrets.API_TOKEN }}"